name: Chris Bates
favicon: null
layout_spectrum: 0.58347
typography_spectrum: 0.51268
title: 'Renegade Theologian, High School English Teacher, and Author'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#bfbfbf'
    - '#dfdfdf'
    - '#434343'
    - '#787878'
  brandStrength: 0.09388943878002465
  lightness: 0.8864509237464517
  saturation: 0.6128010260872543
  rhythmicContrast: 0.75
purpose: []
