name: Chris Bates
favicon: null
layout_spectrum: 0.24874
typography_spectrum: 0.88536
title: 'Renegade Theologian, High School English Teacher, and Author'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#bfbfbf'
    - '#dfdfdf'
    - '#434343'
    - '#787878'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
